from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parent
DATA_DIR = PROJECT_ROOT / "data"
LEVELS_DIR = DATA_DIR / "levels"
GRAPHICS_DIR = PROJECT_ROOT / "graphics"

SCREEN_WIDTH = 1600
SCREEN_CAPTION = "El Monstruo de la Laguna"
SCREEN_BACKGROUND_COLOR = (0, 0, 0)
FPS = 60

TILE_SIZE = 64
TILE_COLOR = (120, 120, 120)

DEFAULT_LEVEL_ID = "level_01"

PLAYER_SPEED = 8
PLAYER_GRAVITY = 0.8
PLAYER_JUMP_SPEED = -16
PLAYER_ANIMATIONS = ("idle", "run", "jump", "fall")

EMPTY_TILE_MARKER = " "
SOLID_TILE_MARKER = "X"
PLAYER_SPAWN_MARKER = "P"
RESERVED_LEVEL_MARKERS = {"A"}
ALLOWED_LEVEL_MARKERS = {
    EMPTY_TILE_MARKER,
    SOLID_TILE_MARKER,
    PLAYER_SPAWN_MARKER,
}.union(RESERVED_LEVEL_MARKERS)

PLACEHOLDER_SURFACE_SIZE = (TILE_SIZE, TILE_SIZE)
PLACEHOLDER_ANIMATION_COLORS = {
    "idle": (60, 170, 220),
    "run": (90, 200, 120),
    "jump": (230, 170, 70),
    "fall": (220, 90, 90),
}
